version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laragigs_app_v2
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:1.25-alpine
    container_name: laragigs_nginx_v2
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laragigs_db_v2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - laragigs_db_data_v2:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  laragigs_db_data_v2:
    driver: local
